Feature/question crud
Helpfy/helpfy-backend pull request #19
Opened 2022-12-03 21:20 UTC by victorbrandaoa

2022-12-04 00:30 UTC, wellissongomes requested changes

2022-12-04 00:30 UTC, wellissongomes commented on src/main/java/com/example/helpfy/controllers/QuestionController.java
> +    @GetMapping("users/{userId}")
Chegou a testar essa rota? Note que `@RequestMapping("/questions")` e `@GetMapping("users/{userId}")` geram o seguinte endpoint: `/questionsusers/{userId}`

2022-12-04 00:30 UTC, wellissongomes commented on src/main/java/com/example/helpfy/models/Question.java
> +    private Set<Long> numberLikes;
Talvez aqui seria melhor `idsFromUsersLikes` ou algo nessa linha. O que acha?

2022-12-04 00:30 UTC, wellissongomes commented on src/main/java/com/example/helpfy/models/Question.java
> +    private Set<Long> numberDislikes;
Mesma sugestão aqui

2022-12-04 00:30 UTC, wellissongomes commented on src/main/java/com/example/helpfy/services/question/QuestionServiceImpl.java
> +    }
Esse método é desnecessário. Veja que se você altera direto em cada set (add e remove), não é necessário atualizar a estrutura de dados novamente. É suficiente a linha 104 (apenas salvar a questão).

2022-12-04 12:32 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/controllers/QuestionController.java
> +    @GetMapping("users/{userId}")
Eu havia testado, então acredito que ele por padrão adiciona a barra no começo da rota, mas corrigi pra manter o padrão.

2022-12-04 12:32 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/models/Question.java
> +    private Set<Long> numberLikes;
Feito.

2022-12-04 12:32 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/models/Question.java
> +    private Set<Long> numberDislikes;
Feito.

2022-12-04 12:32 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/question/QuestionServiceImpl.java
> +    }
Refatorei e removi esse método.

2022-12-04 15:26 UTC, wellissongomes commented
Ainda há alguns pontos a serem corrigidos:

1. Se um user da like/dislike, ele não consegue remover.
2. Há um bug quando é enviado mudanças na questão. Se eu mando um `answered: true` e depois faço um novo update sem esse campo, ele volta a ser false. É melhor criar um endpoint especifico para saber se foi respondida ou não.
3. Alterar todas as rotas que estão com o verbo PUT para PATCH.

2022-12-05 22:20 UTC, wellissongomes approved these changes

2022-12-05 22:20 UTC, merged