added question search endpoint and filter options
Helpfy/helpfy-backend pull request #22
Opened 2022-12-14 16:31 UTC by pedrohos

2022-12-16 13:41 UTC, victorbrandaoa requested changes
Deixei alguns poucos comentários.

2022-12-16 13:41 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/controllers/QuestionSearchController.java
> +    @Autowired
A anotation `@Autowired` está deprecated, atualmente o que fazemos é criar os construtores das classes.

2022-12-16 13:41 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/controllers/QuestionSearchController.java
> +                                                         @RequestParam(defaultValue = "new") String filter) {
Acho que esse parâmetro `filtro` está mais relacionado com a ordenação, não? Acho que um nome melhor seria algo como `order`.

2022-12-16 13:41 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/search/QuestionSearchServiceImpl.java
> +    public static final String NEW = "new";
Apenas uma sugestão, mas talvez seja interessante colocar em um arquivo de constantes ou como os valores são fixos, poderia até mesmo ser um ENUM.

2022-12-16 18:48 UTC, wellissongomes commented
Eu fiz uma mudança no código pois quando pesquisavamos por um titulo, nunca usava a similaridade porque ele ordenava pela data sempre. Além disso, coloquei o minimo de 10% de similaridade no título para não haver caso de vir questões nada a ver com o que o user busca.

No mais, acredito que está ok. Você pode ficar livre para alterar se quiser o que Victor pediu.

2022-12-16 18:49 UTC, wellissongomes approved these changes

2022-12-16 18:56 UTC, ericdmg commented
Eu revisei o PR em conjunto com Victor, as considerações dele são as mesmas das minhas.

2022-12-17 19:27 UTC, ericdmg approved these changes

2022-12-18 14:11 UTC, victorbrandaoa approved these changes
LGTM!

2022-12-18 14:11 UTC, merged