Feat/comment crud
Helpfy/helpfy-backend pull request #24
Opened 2022-12-16 18:49 UTC by ericdmg

CRUD de comentário feito. 

Procurei seguir o padrão de validação das entidades, mas em um momento optei por criar um método auxiliar e só ficar reutilizando-o porque estava tendo muita duplicação de código.

2022-12-16 22:07 UTC, victorbrandaoa requested changes
Deixei algumas sugestões e uns comentários com dúvidas. No mais, LGTM!

2022-12-16 22:07 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        answerRepository.save(answer);
Essa linha é necessária? Acho que `answer` não foi editado.

2022-12-16 22:07 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        questionRepository.save(question);
Essa linha é necessária? Acho que `question` não foi editado.

2022-12-16 22:07 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/controllers/CommentController.java
> +public class CommentController {
Uma sugestão geral para o controller e para o service é utilizar a palavra-chave `var` que foi adicionada ao Java, mais como forma de padronizar o backend, você pode encontrar exemplos disso, nos outros controllers e nos outros service.

2022-12-17 00:59 UTC, wellissongomes requested changes

2022-12-17 00:59 UTC, wellissongomes commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +
Adiciona as notações `@Override` e ` @Transactional`.

2022-12-17 00:59 UTC, wellissongomes commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        comment.setAuthor(user);
Por que está alterando o autor quando adicionar um comentário na resposta? Não me parece correto.

2022-12-17 00:59 UTC, wellissongomes commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        checkIfEntityHasComment(answer.getComments(), comment);
Bom manter a consistência. Ou usa o `this` aqui, ou remove da linha 86.

2022-12-17 00:59 UTC, wellissongomes commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        answerRepository.save(answer);
Concordo. É suficiente alterar apenas o comentário. Note que com isso, não será necessário passar `answer` como parâmetro. No controller você pode apenas chamar (sem atribuir) o método `answerService.getAnswerById(answerId);` apenas para verificar se existe a resposta.

2022-12-17 00:59 UTC, wellissongomes commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        comment.setAuthor(user);
Não é necessário o `user` nesse método.

2022-12-17 00:59 UTC, wellissongomes commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +
Adiciona as notações `@Override` e `@Transactional`.

2022-12-17 00:59 UTC, wellissongomes commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +    @Override
Adiciona a notação `@Transactional`.

2022-12-17 00:59 UTC, wellissongomes commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        questionRepository.save(question);
Concordo.

2022-12-17 20:34 UTC, victorbrandaoa approved these changes
Aprovei, mas deixei algumas sugestões.

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/controllers/CommentController.java
> +        Answer answer = answerService.getAnswerById(answerId);
```suggestion
        var answer = answerService.getAnswerById(answerId);
```

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/controllers/CommentController.java
> +public class CommentController {
Apenas uma sugestão, mas tem alguns lugares que usar o `this` para referenciar os atributos e outros não, talvez seja interessante padronizar.

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/controllers/CommentController.java
> +        Question question = questionService.getQuestionById(questionId);
```suggestion
        var question = questionService.getQuestionById(questionId);
```

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentService.java
> +    Comment deleteCommentQuestion(Long commentId, Question question);
Acho que o método de delete poderia ser `void`, para as outras entidades, não estamos retornando a entidade deletada.

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentService.java
> +    Comment deleteCommentAnswer(Long commentId, Answer answer);
Acho que o método de delete poderia ser `void`, para as outras entidades, não estamos retornando a entidade deletada.

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        Comment comment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```suggestion
        var comment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        Comment originalComment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```suggestion
        var originalComment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        Comment comment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```suggestion
        var comment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        Comment comment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```suggestion
        var comment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        Comment originalComment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```suggestion
        var originalComment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```

2022-12-17 20:34 UTC, victorbrandaoa commented on src/main/java/com/example/helpfy/services/comment/CommentServiceImpl.java
> +        Comment comment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```suggestion
        var comment = findById(commentId, commentRepository, Constants.COMMENT_NOT_FOUND);
```

2022-12-17 22:09 UTC, ericdmg commented
> Deixei algumas sugestões e uns comentários com dúvidas. No mais, LGTM!

Sobre `var`, já coloquei em todo lugar, acho que você estava olhando commits antigos

2022-12-17 23:51 UTC, wellissongomes approved these changes

2022-12-17 23:52 UTC, merged